/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calcu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author HP
 */
public class Calcudis extends javax.swing.JFrame {

    String memoria1,memoria2,signo;
    
    /**
     * Creates new form Calcudis
     */
    public Calcudis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Panel_Principal = new javax.swing.JPanel();
        bt_1 = new javax.swing.JButton();
        bt_2 = new javax.swing.JButton();
        bt_4 = new javax.swing.JButton();
        bt_3 = new javax.swing.JButton();
        bt_5 = new javax.swing.JButton();
        bt_6 = new javax.swing.JButton();
        bt_7 = new javax.swing.JButton();
        bt_8 = new javax.swing.JButton();
        bt_9 = new javax.swing.JButton();
        bt_0 = new javax.swing.JButton();
        bt_punto = new javax.swing.JButton();
        bt_igual = new javax.swing.JButton();
        bt_mas = new javax.swing.JButton();
        bt_menos = new javax.swing.JButton();
        bt_por = new javax.swing.JButton();
        bt_div = new javax.swing.JButton();
        bt_ce = new javax.swing.JButton();
        txt_valor = new javax.swing.JTextField();
        lbl_calcu = new javax.swing.JLabel();
        bt_historial = new javax.swing.JButton();
        Panel_instr = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_1.setBackground(new java.awt.Color(102, 0, 204));
        bt_1.setForeground(new java.awt.Color(255, 255, 255));
        bt_1.setText("1");
        bt_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_1ActionPerformed(evt);
            }
        });

        bt_2.setBackground(new java.awt.Color(102, 0, 204));
        bt_2.setForeground(new java.awt.Color(255, 255, 255));
        bt_2.setText("2");
        bt_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_2ActionPerformed(evt);
            }
        });

        bt_4.setBackground(new java.awt.Color(102, 0, 204));
        bt_4.setForeground(new java.awt.Color(255, 255, 255));
        bt_4.setText("4");
        bt_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_4ActionPerformed(evt);
            }
        });

        bt_3.setBackground(new java.awt.Color(102, 0, 204));
        bt_3.setForeground(new java.awt.Color(255, 255, 255));
        bt_3.setText("3");
        bt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_3ActionPerformed(evt);
            }
        });

        bt_5.setBackground(new java.awt.Color(102, 0, 204));
        bt_5.setForeground(new java.awt.Color(255, 255, 255));
        bt_5.setText("5");
        bt_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_5ActionPerformed(evt);
            }
        });

        bt_6.setBackground(new java.awt.Color(102, 0, 204));
        bt_6.setForeground(new java.awt.Color(255, 255, 255));
        bt_6.setText("6");
        bt_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_6ActionPerformed(evt);
            }
        });

        bt_7.setBackground(new java.awt.Color(102, 0, 204));
        bt_7.setForeground(new java.awt.Color(255, 255, 255));
        bt_7.setText("7");
        bt_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_7ActionPerformed(evt);
            }
        });

        bt_8.setBackground(new java.awt.Color(102, 0, 204));
        bt_8.setForeground(new java.awt.Color(255, 255, 255));
        bt_8.setText("8");
        bt_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_8ActionPerformed(evt);
            }
        });

        bt_9.setBackground(new java.awt.Color(102, 0, 204));
        bt_9.setForeground(new java.awt.Color(255, 255, 255));
        bt_9.setText("9");
        bt_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_9ActionPerformed(evt);
            }
        });

        bt_0.setBackground(new java.awt.Color(102, 0, 204));
        bt_0.setForeground(new java.awt.Color(255, 255, 255));
        bt_0.setText("0");
        bt_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_0ActionPerformed(evt);
            }
        });

        bt_punto.setBackground(new java.awt.Color(102, 0, 204));
        bt_punto.setForeground(new java.awt.Color(255, 255, 255));
        bt_punto.setText(".");
        bt_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_puntoActionPerformed(evt);
            }
        });

        bt_igual.setBackground(new java.awt.Color(102, 0, 204));
        bt_igual.setForeground(new java.awt.Color(255, 255, 255));
        bt_igual.setText("=");
        bt_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_igualActionPerformed(evt);
            }
        });

        bt_mas.setBackground(new java.awt.Color(102, 0, 204));
        bt_mas.setForeground(new java.awt.Color(255, 255, 255));
        bt_mas.setText("+");
        bt_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_masActionPerformed(evt);
            }
        });

        bt_menos.setBackground(new java.awt.Color(102, 0, 204));
        bt_menos.setForeground(new java.awt.Color(255, 255, 255));
        bt_menos.setText("-");
        bt_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menosActionPerformed(evt);
            }
        });

        bt_por.setBackground(new java.awt.Color(102, 0, 204));
        bt_por.setForeground(new java.awt.Color(255, 255, 255));
        bt_por.setText("*");
        bt_por.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_porActionPerformed(evt);
            }
        });

        bt_div.setBackground(new java.awt.Color(102, 0, 204));
        bt_div.setForeground(new java.awt.Color(255, 255, 255));
        bt_div.setText("/");
        bt_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_divActionPerformed(evt);
            }
        });

        bt_ce.setBackground(new java.awt.Color(255, 102, 51));
        bt_ce.setForeground(new java.awt.Color(255, 255, 255));
        bt_ce.setText("CE");
        bt_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ceActionPerformed(evt);
            }
        });

        lbl_calcu.setText("Calculadora");

        bt_historial.setBackground(new java.awt.Color(102, 102, 102));
        bt_historial.setForeground(new java.awt.Color(102, 255, 51));
        bt_historial.setText("Historial");
        bt_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addComponent(lbl_calcu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 50, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                        .addComponent(bt_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PrincipalLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_por, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(bt_div, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                                .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_ce)
                            .addComponent(bt_historial))
                        .addGap(28, 28, 28))))
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_calcu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_mas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_por, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(bt_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_div, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculadora", Panel_Principal);

        Panel_instr.setBackground(new java.awt.Color(0, 102, 102));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 102, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("ingresa los numeros que quieras dale \na sumar o restar presiona igual y se realizara \nla operacion. si quieres ver el historial puedes \nusar el atajo de abajo  o darle a opciones y manual");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Manual de usuario");

        javax.swing.GroupLayout Panel_instrLayout = new javax.swing.GroupLayout(Panel_instr);
        Panel_instr.setLayout(Panel_instrLayout);
        Panel_instrLayout.setHorizontalGroup(
            Panel_instrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_instrLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_instrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        Panel_instrLayout.setVerticalGroup(
            Panel_instrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_instrLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Instrucciones", Panel_instr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_7ActionPerformed
    
        Audio.play();
        txt_valor.setText(txt_valor.getText()+"7");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_7ActionPerformed

    private void bt_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_masActionPerformed
            // TODO add your handling code here:
            Audio.play();
            if (!txt_valor.getText().equals("")){
                memoria1=txt_valor.getText();
                signo="+";
                txt_valor.setText("");
                
            }
    }//GEN-LAST:event_bt_masActionPerformed

    private void bt_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_8ActionPerformed
    Audio.play();
        txt_valor.setText(txt_valor.getText()+"8");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_8ActionPerformed

    private void bt_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_1ActionPerformed
        Audio.play();
        txt_valor.setText(txt_valor.getText()+"1");
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_1ActionPerformed

    private void bt_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_2ActionPerformed
    Audio.play();
        txt_valor.setText(txt_valor.getText()+"2");
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_2ActionPerformed

    private void bt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_3ActionPerformed
    Audio.play();
        txt_valor.setText(txt_valor.getText()+"3");    // TODO add your handling code here:
    }//GEN-LAST:event_bt_3ActionPerformed

    private void bt_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_4ActionPerformed
    
        Audio.play();
        txt_valor.setText(txt_valor.getText()+"4");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_4ActionPerformed

    private void bt_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_5ActionPerformed
    Audio.play();
    txt_valor.setText(txt_valor.getText()+"5");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_5ActionPerformed

    private void bt_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_6ActionPerformed
    Audio.play();
    txt_valor.setText(txt_valor.getText()+"6");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_6ActionPerformed

    private void bt_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_9ActionPerformed
    Audio.play();
    txt_valor.setText(txt_valor.getText()+"9");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_9ActionPerformed

    private void bt_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_0ActionPerformed
    Audio.play();
    txt_valor.setText(txt_valor.getText()+"0");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_0ActionPerformed

    private void bt_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_divActionPerformed
        // TODO add your handling code here:
        Audio.play();
                    if (!txt_valor.getText().equals("")){
                memoria1=txt_valor.getText();
                signo="/";
                txt_valor.setText("");
                
            }
    }//GEN-LAST:event_bt_divActionPerformed

    private void bt_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_puntoActionPerformed
   Audio.play();
        String pnt;
    pnt = txt_valor.getText();
    if (pnt.length()<=0){
        txt_valor.setText("0.");
    }
    else{
        if (!puntoex(txt_valor.getText())){
            txt_valor.setText(txt_valor.getText()+".");
        }
    }
// TODO add your handling code here:
    }//GEN-LAST:event_bt_puntoActionPerformed

    private void bt_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ceActionPerformed
    Audio.play();
        txt_valor.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ceActionPerformed

    private void bt_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menosActionPerformed
        // TODO add your handling code here:
        Audio.play();
                    if (!txt_valor.getText().equals("")){
                memoria1=txt_valor.getText();
                signo="-";
                txt_valor.setText("");
                
            }
    }//GEN-LAST:event_bt_menosActionPerformed

    private void bt_porActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_porActionPerformed
        // TODO add your handling code here:
        Audio.play();
                    if (!txt_valor.getText().equals("")){
                memoria1=txt_valor.getText();
                signo="*";
                txt_valor.setText("");
                
            }
    }//GEN-LAST:event_bt_porActionPerformed

    private void bt_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_igualActionPerformed
        String resultado;
        Audio.play();
        memoria2=txt_valor.getText();
        if (!memoria2.equals("")){
            resultado = calculadora (memoria1,memoria2,signo);
            txt_valor.setText(resultado);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_igualActionPerformed

    private void bt_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_historialActionPerformed
    Historial calcu = new Historial();
        calcu.show();   
// TODO add your handling code here:
    }//GEN-LAST:event_bt_historialActionPerformed
    public static String calculadora(String memoria1,String memoria2, String signo){
        Double resultado =0.0;
        String respuesta;
        
        if (signo.equals("-")){
            resultado=Double.parseDouble(memoria1)- Double.parseDouble(memoria2);
        }
        if (signo.equals("+")){
            resultado=Double.parseDouble(memoria1)+ Double.parseDouble(memoria2);
        }
        if (signo.equals("*")){
            resultado=Double.parseDouble(memoria1)* Double.parseDouble(memoria2);
        }
        if (signo.equals("/")){
            resultado=Double.parseDouble(memoria1)/ Double.parseDouble(memoria2);
        }
        respuesta=resultado.toString();
        return respuesta;
    }
    
    
    public static boolean puntoex(String pnt){
    boolean resultado;
    resultado=false;
    for (int i = 0; i<pnt.length(); i++){
        if (pnt.substring(i,i+1).equals(".")){
            resultado = true;
        }
    }
    return resultado;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcudis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcudis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcudis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcudis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcudis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_instr;
    private javax.swing.JButton bt_0;
    private javax.swing.JButton bt_1;
    private javax.swing.JButton bt_2;
    private javax.swing.JButton bt_3;
    private javax.swing.JButton bt_4;
    private javax.swing.JButton bt_5;
    private javax.swing.JButton bt_6;
    private javax.swing.JButton bt_7;
    private javax.swing.JButton bt_8;
    private javax.swing.JButton bt_9;
    private javax.swing.JButton bt_ce;
    private javax.swing.JButton bt_div;
    private javax.swing.JButton bt_historial;
    private javax.swing.JButton bt_igual;
    private javax.swing.JButton bt_mas;
    private javax.swing.JButton bt_menos;
    private javax.swing.JButton bt_por;
    private javax.swing.JButton bt_punto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_calcu;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
